name: Build phantomake binary
on:
  push:
    tags:
      - '*'
jobs:
  build-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            binary-name: macos
          - os: ubuntu-latest
            binary-name: linux
    permissions:
      contents: write
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Bun install
        run: |
          bun install
      - name: Build phantomake
        run: |
          bun build-cli
          mv phantomake phantomake-${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v3
        with:
          name: phantomake-${{ matrix.binary-name }}
          path: phantomake-${{ matrix.binary-name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: phantomake-${{ matrix.binary-name }}
