name: Build phantomake binary
on:
  push:
    tags:
      - '*'
jobs:
  build-binary-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            binary-name: macos
          - os: ubuntu-latest
            binary-name: linux
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./packages/phantomake/
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Bun install
        run: |
          bun install
      - name: Build phantomake
        run: |
          bun run build
          tar -zcvf phantomake-${{ matrix.binary-name }}.tar.gz phantomake
      - uses: actions/upload-artifact@v3
        with:
          name: phantomake-${{ matrix.binary-name }}.tar.gz
          path: ./packages/phantomake/phantomake-${{ matrix.binary-name }}.tar.gz
      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: phantomake-${{ matrix.binary-name }}.tar.gz
  build-binary-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./packages/docs/
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Bun install
        run: |
          bun install
      - name: Build phantomake (Windows)
        run: |
          bun run build
          Compress-Archive -Path phantomake.exe -Destination phantomake-windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: phantomake-windows.zip
          path: ./packages/phantomake/phantomake-windows.zip
      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: phantomake-windows.zip
  upload-source:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Make source tarball
        run: |
          git archive --format=tar.gz -o source.tar.gz --prefix=phantomake/ HEAD
      - name: Upload tarball to release
        uses: softprops/action-gh-release@v1
        with:
          files: source.tar.gz
